// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportDashboard.DataAccessLayer.Concrete;

#nullable disable

namespace ReportDashboard.DataAccessLayer.Migrations
{
    [DbContext(typeof(ReportDashboardContext))]
    partial class ReportDashboardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportDashboard.EntityLayer.Entities.DbTable", b =>
                {
                    b.Property<int>("DbTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbTableID"));

                    b.Property<string>("DbTable_Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbTable_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbTable_ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbTable_UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DbTableID");

                    b.ToTable("DbTables");
                });

            modelBuilder.Entity("ReportDashboard.EntityLayer.Entities.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int?>("DbTableID")
                        .HasColumnType("int");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.HasIndex("DbTableID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportDashboard.EntityLayer.Entities.Report", b =>
                {
                    b.HasOne("ReportDashboard.EntityLayer.Entities.DbTable", "DbTable")
                        .WithMany("Reports")
                        .HasForeignKey("DbTableID");

                    b.Navigation("DbTable");
                });

            modelBuilder.Entity("ReportDashboard.EntityLayer.Entities.DbTable", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
